{% set name = "poetry-plugin-export" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry_plugin_export-{{ version }}.tar.gz
  sha256: 1fa6168a85d59395d835ca564bc19862a7c76061e60c3e7dfaec70d50937fc61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0.0
    - poetry-core >=1.7.0,<3.0.0
    # warning: this is a circular dependency.  If this causes trouble (e.g.
    # there is an update that simultaneously requires a new poetry and
    # poetry-plugin-export, temporarly switch this to "run_constrained"
    - poetry >=1.8.0,<3.0.0

# Skip tests partially due to dependency cycle (see above):
#   File/version check instead of import test; ignored poetry dep in pip check
test:
  # imports:
  #   - poetry_plugin_export
  commands:
    - test -f "${SP_DIR}"/poetry_plugin_export/__init__.py
    - "pip show poetry-plugin-export | grep -Fx 'Version: {{ version }}'"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/poetry-plugin-export/
  summary: Poetry plugin to export the dependencies to various formats
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-poetry/poetry-plugin-export

extra:
  recipe-maintainers:
    - xylar
    - maresb
