{% set name = "poetry-plugin-export" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry_plugin_export-{{ version }}.tar.gz
  sha256: cf62cfb6218a904290ba6db3bc1a24aa076d10f81c48c6e48b2ded430131e22e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0,<4.0.0
    - pip
    - poetry-core
  run:
    - python >=3.8.0,<4.0.0
    - poetry-core >=1.7.0,<2.0.0
  # poetry is actually a run dependency. But since that creates a dependency
  # cycle, we add it only as a run_constrained for now (until fixed upstream).
  # (N.B.: This means this package is unusable if `conda install`ed on its own.)
  # refs:
  #  - https://github.com/python-poetry/poetry/pull/5980
  #  - https://github.com/conda-forge/poetry-feedstock/issues/70
  run_constrained:
    - poetry >=1.8.0,<2.0.0

# Skip tests partially due to dependency cycle (see above):
#   File/version check instead of import test; ignored poetry dep in pip check
test:
  # imports:
  #   - poetry_plugin_export
  commands:
    - test -f "${SP_DIR}"/poetry_plugin_export/__init__.py
    - "pip show poetry-plugin-export | grep -Fx 'Version: {{ version }}'"
    # Ensure pip check has non-empty output and recognizes the missing dep.
    - pip check | grep -F 'requires poetry, which is not installed.'
    # Ensure pip check does not output anything else. (This includes
    # "No broken requirements found." -- a signal to update the recipe ;)
    - "! pip check | grep -Fv 'requires poetry, which is not installed.'"
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-plugin-export/
  summary: Poetry plugin to export the dependencies to various formats
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-poetry/poetry-plugin-export

extra:
  recipe-maintainers:
    - xylar
    - maresb
