{% set name = "poetry-plugin-export" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poetry_plugin_export-{{ version }}.tar.gz
  sha256: 6fc8755cfac93c74752f85510b171983e2e47d782d4ab5be4ffc4f6945be7967

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0.0
    - poetry-core >=1.7.0,<3.0.0
    - poetry >=2.0.0,<3.0.0

test:
  imports:
    - poetry_plugin_export
  commands:
    - test -f "${SP_DIR}"/poetry_plugin_export/__init__.py
    - "pip show poetry-plugin-export | grep -Fx 'Version: {{ version }}'"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/poetry-plugin-export/
  summary: Poetry plugin to export the dependencies to various formats
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-poetry/poetry-plugin-export

extra:
  recipe-maintainers:
    - xylar
    - maresb
