{% set name = "poetry-plugin-export" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-plugin-export-{{ version }}.tar.gz
  sha256: 23e3e512a609b54ef5ac441339fc9e68fd41e61d15bd924eb0094b4fda1e30d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry-core
  run:
    - python >=3.7,<4.0
    - poetry >=1.2.0b3,<2.0.0
    - poetry-core >=1.1.0b3,<2.0.0

test:
  imports:
    - poetry_plugin_export
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-plugin-export/
  summary: Poetry plugin to export the dependencies to various formats
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-poetry/poetry-plugin-export

extra:
  recipe-maintainers:
    - xylar
    - maresb
